prometheus:
  http-sd:
    cidrs:
      - "192.168.0.0/16"
      - "fe80::/10"
    hosts:
      - "marmot-01.local"

"%dev":
  quarkus:
    log:
      category:
        "com.joshdreagan":
          level: DEBUG
  prometheus:
    http-sd:
      hosts:
        - "marmot-01.local"
        - "camel-01.local"
