"%dev":
  quarkus:
    log:
      category:
        "com.joshdreagan":
          level: DEBUG
  prometheus:
    http-sd:
      hosts:
        - "marmot-01.local:9100"
        #- "camel-01.local:9100"
      resolve-hosts: true
      skip-unknown-hosts: true
      cidrs:
        - "192.168.0.0/16"
        - "fe80::/10"
      skip-unmatched-hosts: true
